project:
  type: website

website:
  title: "Climate Gazette"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/ifabfoundation/e3ci-workshop
  page-footer:
    left: "© 2026 Climate Gazette"
    right:
      - icon: envelope
        href: mailto:you@example.com

format:
  html:
    css: styles.css